# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# Java
jvm-jdk = "21"
jvm-compatibility = "17"

# Jetbrains
kotlin = "2.3.0"
ksp = "2.3.4"
ktor = "3.4.0"
kotlinx-rpc = "0.10.1"
exposed = "1.0.0"
kotlinx-io = "0.8.1"

# Spring
spring-boot = "4.0.2"
spring-cloud = "2025.1.0"
spring-shell = "3.4.0"

# KMP
multiplatform-settings = "1.3.0"
compose-hotReload = "1.0.0-beta07"
compose-multiplatform = "1.9.0"
kmp-notifier = "1.6.0"
agp = "8.11.2"
compose-native-tray = "1.0.4"
androidx-lifecycle = "2.9.4"
kmp-locale = "0.9.0"
cryptography = "0.5.0"
metro = "0.10.0"
clikt = "5.0.3"
config4k = "0.7.0"
koin = "4.1.1"
i18n4k = "0.11.1"
# TODO :: kourier 제거
kourier = "0.4.1"
konform = "0.11.1"
serial-schema = "0.1.0-SNAPSHOT"
spatialk = "0.6.1"

# JVM
argon2-jvm = "2.12"
jib = "3.5.2"

# logging
kotlin-logging = "7.0.13"
logback = "1.5.15"
slf4j = "2.0.16"
log4j = "2.25.3"

# lint
kotlinter = "5.0.1"
detekt = "1.23.8"

# test
## kotest
kotest = "6.0.3"
kotestExtensionsSpring = "1.3.0"
## mockk
mockk = "1.14.6"
springMockk = "4.0.2"
## testcontainers
testcontainers = "1.20.2"

# rabbitmq server 버전 올릴때, 문서에 erlang 버전도 같이 수정해주어야 함.
rabbitmq-server = "4.2.2"
rabbitmq-client = "5.28.0"

# GIS
locationtech-proj4j = "1.1.3"
locationtech-jts = "1.19.0"
geotools = "34.0"
geotools-xsd = "33.2"
gdal = "3.12.2"

jodaTime = "2.10.13"

# protobuf, grpc
protobuf-plugin = "0.9.5"
protobuf = "4.33.0"
grpc = "1.70.0"
grpc-kotlin = "1.5.0"
grpc-compatibility = "1.68.1"
armeria = "1.35.0"

shadow = "9.1.0"

hibernate-types = "3.15.1"
embedded-postgres-zonky = "2.2.0"
embedded-rabbitmq-arivera = "1.5.0"
debezium = "3.4.0.Final"

tomlj = "1.1.1"
versionCatalog-generator = "3.4.0"
foojay-resolverConvention = "1.0.0"

[plugins]
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-plugin-noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "kotlin" }
kotlin-plugin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-plugin-rpc = { id = "org.jetbrains.kotlinx.rpc.plugin", version.ref = "kotlinx-rpc" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
idea = { id = "org.gradle.idea" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.7.0" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hotReload" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
i18n4k = { id = "de.comahe.i18n4k", version.ref = "i18n4k" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }


[libraries]
kotlinx-serialization-bom = { module = "org.jetbrains.kotlinx:kotlinx-serialization-bom", version = "1.9.0" } # for override version
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }
spring-shell-dependencies = { module = "org.springframework.shell:spring-shell-dependencies", version.ref = "spring-shell" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
armeria-bom = { module = "com.linecorp.armeria:armeria-bom", version.ref = "armeria" }
kotest-bom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
exposed-bom = { module = "org.jetbrains.exposed:exposed-bom", version.ref = "exposed" }
geotools-bom = { module = "org.geotools:gt-bom", version.ref = "geotools" }
grpc-bom = { module = "io.grpc:grpc-bom", version.ref = "grpc" }
kotlinx-rpc-bom = { module = "org.jetbrains.kotlinx:kotlinx-rpc-bom", version.ref = "kotlinx-rpc" }
cryptography-bom = { module = "dev.whyoleg.cryptography:cryptography-bom", version.ref = "cryptography" }
log4j-bom = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "log4j" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
debezium-bom = { module = "io.debezium:debezium-bom", version.ref = "debezium" } # bom 을 넣으면 안된다?
embedded-postgres-binaries-bom = { module = "io.zonky.test.postgres:embedded-postgres-binaries-bom", version = "18.1.0" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-native-utils = { module = "org.jetbrains.kotlin:kotlin-native-utils", version.ref = "kotlin" }
i18n4k-core = { module = "de.comahe.i18n4k:i18n4k-core", version.ref = "i18n4k" }
metro-runtime = { module = "dev.zacsweers.metro:runtime", version.ref = "metro" }
geotools-xsd-kml = { module = "org.geotools.xsd:gt-xsd-kml", version.ref = "geotools-xsd" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
kmp-notifier = { module = "io.github.mirzemehdi:kmpnotifier", version.ref = "kmp-notifier" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
compose-native-tray = { module = "io.github.kdroidfilter:composenativetray", version.ref = "compose-native-tray" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
gdal = { module = "org.gdal:gdal", version.ref = "gdal" }
gdal-gdal = { module = "org.gdal:gdal", version.ref = "gdal" }
locationtech-proj4j = { module = "org.locationtech.proj4j:proj4j", version.ref = "locationtech-proj4j" }
locationtech-jts-core = { module = "org.locationtech.jts:jts-core", version.ref = "locationtech-jts" }
locationtech-jts-io-common = { module = "org.locationtech.jts.io:jts-io-common", version.ref = "locationtech-jts" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
jodaTime-jodaTime = { module = "joda-time:joda-time", version.ref = "jodaTime" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
grpc-protoc-gen-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }
grpc-protoc-gen-kotlin = { module = "io.grpc:protoc-gen-grpc-kotlin", version.ref = "grpc-kotlin" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin" }
config4k = { module = "io.github.config4k:config4k", version.ref = "config4k" }
hibernate-types = { module = "io.hypersistence:hypersistence-utils-hibernate-70", version.ref = "hibernate-types" }
detekt-ktlint = { module = "io.gitlab.arturbosch.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }
tomlj = { group = "org.tomlj", name = "tomlj", version.ref = "tomlj" }
kmp-locale = { module = "com.vanniktech:multiplatform-locale", version.ref = "kmp-locale" }
argon2-jvm = { module = "de.mkammerer:argon2-jvm", version.ref = "argon2-jvm" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
clikt-markdown = { module = "com.github.ajalt.clikt:clikt-markdown", version.ref = "clikt" }
postgresql-postgresql = { module = "org.postgresql:postgresql", version = "42.7.8" }
embedded-postgres = { module = "io.zonky.test:embedded-postgres", version.ref = "embedded-postgres-zonky" }
embedded-rabbitmq = { module = "io.arivera.oss:embedded-rabbitmq", version.ref = "embedded-rabbitmq-arivera" }
debezium-api = { module = "io.debezium:debezium-api", version.ref = "debezium" }
debezium-embedded = { module = "io.debezium:debezium-embedded", version.ref = "debezium" }
debezium-connector-postgres = { module = "io.debezium:debezium-connector-postgres", version.ref = "debezium" }
kourier-client = { module = "dev.kourier:amqp-client", version.ref = "kourier" }
kourier-client-robust = { module = "dev.kourier:amqp-client-robust", version.ref = "kourier" }
kourier-client-opentelemetry = { module = "dev.kourier:amqp-client-opentelemetry", version.ref = "kourier" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinx-io" }
kotlinx-io-okio = { module = "org.jetbrains.kotlinx:kotlinx-io-okio", version.ref = "kotlinx-io" }
rabbitmq-client-amqp = { module = "com.rabbitmq:amqp-client", version.ref = "rabbitmq-client" }
konform = { module = "io.konform:konform", version.ref = "konform" }
spatialk = { module = "org.maplibre.spatialk:geojson", version.ref = "spatialk" }


gradlePlugin-versionCatalog-generator = { group = "dev.aga.gradle.version-catalog-generator", name = "dev.aga.gradle.version-catalog-generator.gradle.plugin", version.ref = "versionCatalog-generator" }
gradlePlugin-foojay-resolverConvention = { module = "org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin", version.ref = "foojay-resolverConvention" }
gradlePlugin-kotlin-multiplatform = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
gradlePlugin-kotlin-jvm = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
gradlePlugin-detekt = { module = "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }
gradlePlugin-shadow = { module = "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin", version.ref = "shadow" }

[bundles]
# 라이브러리가 겹칠 경우, 먼저 선언된 버전을 사용
boms-for-generate-versionCatalogs = [
    "testcontainers-bom",
    "kotlinx-serialization-bom", # for override version
    "spring-boot-dependencies",
    "spring-cloud-dependencies",
    "spring-shell-dependencies",
    "ktor-bom",
    "armeria-bom",
    "kotest-bom",
    "koin-bom",
    "exposed-bom",
    "geotools-bom",
    "grpc-bom",
    "kotlinx-rpc-bom",
    "cryptography-bom",
    "log4j-bom",
    "embedded-postgres-binaries-bom"
]
